baseurl: "https://sweatequity.jp"
title: "Sweat Equity Partners"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "public"
metaDataFormat: "yaml"
languageCode: "ja"
permalinks:
  post: "/:year/:title"
markup:
  goldmark:
    renderer:
      unsafe: true